### ISSUE TITLE
"mocks/token/..." folder not in soldeer openzeppelin-contracts

### ISSUE THREAD

**Issue by sergio-27** [mario-eth/soldeer#166]
Hi, is it posible that the folder mocks is not in the openzeppelin contracts repo from soldeer?? It appears in the original repository from openzeppelin but not in the openzeppelin libraries from soldeer.

This two images are from the source code from soldeer
![Captura de pantalla 2024-08-28 a las 15 13 10](https://github.com/user-attachments/assets/41317d5b-3f37-445c-abd3-3db4c2bd9b1a)
![Captura de pantalla 2024-08-28 a las 15 13 21](https://github.com/user-attachments/assets/9c06403f-ba34-419b-bf43-9762708f0684)

And this is the original repo of openzeppelin contracts.
<img width="1713" alt="Captura de pantalla 2024-08-28 a las 15 12 52" src="https://github.com/user-attachments/assets/ddb94313-60a6-4d33-a7b5-ff44a406a94f">

**Comment by mario-eth** [comment]
hey, unfortunately that is not present in the official release on npm.  After some discussions with the OZ team, they said that the mocks should not be used and they are present just on github and not on the official release so that people don't use them in production.

If you really want to use them you can use the git way of installing this, something like:
`forge soldeer install @openzeppelin-mocks~5.0.2 https://github.com/OpenZeppelin/openzeppelin-contracts.git`

And now you have a specific oz version from git that has the mocks that can be used only for testing

**Comment by sergio-27** [comment]
Okey, make sense, its just what i did, thanks for replying!!
